# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
   name: Default
   environment: playtest

steps:
- task: UnitySetupTask@2
  inputs:
    installWebGLModule: true

- task: UnityBuildTask@3
  inputs:
    buildTarget: 'WebGL'
    outputPath: '$(Build.BinariesDirectory)'
    outputFileName: 'drop'


- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.BinariesDirectory)'
    Contents: '**'
    TargetFolder: '/games/build'
