trigger:
- master

pool:
 name: self-hosted

jobs:
- job: Build
  displayName: 'Build and Deploy to Playtest Environment'

- deployment: DeployPlaytest
  displayName: 'Deploy to Playtest Environment'
  environment: 'playtest'  # This is where you specify your environment
  dependsOn: Build  # Ensures the DeployPlaytest job runs after the Build job
  strategy:
    runOnce:
      deploy:
        steps:
        - task: UnitySetupTask@2
          inputs:
            installWebGLModule: true

        - task: UnityBuildTask@3
          inputs:
            buildTarget: 'WebGL'
            outputPath: '$(Build.BinariesDirectory)'
            outputFileName: 'drop'

        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(Build.BinariesDirectory)'
            Contents: '**'
            TargetFolder: '/games/build'