trigger:
- master

pool:
 name: self-hosted

jobs:
- job: Build
  displayName: 'Build and Deploy to Playtest Environment'

- deployment: DeployPlaytest
  displayName: 'Deploy to Playtest Environment'
  environment: 'playtest'  # This is where you specify your environment
  dependsOn: Build  # Ensures the DeployPlaytest job runs after the Build job
  strategy:
    runOnce:
      deploy:
        steps:
        - task: UnityBuildTask@3
          inputs:
            unityEditorsPathMode: 'specify'
            customUnityEditorsPath: '/home/Unity/Hub/Editor/6000.0.33f1/Editor/'
            unityProjectPath: '/home//projects/RevolvingChambers'
            buildTarget: 'WebGL'
            outputPath: '/home//projects/RevolvingChambers/build'
            outputFileName: 'game'